In [69]:
import pandas as pd
import matplotlib.pyplot as plt
from pymongo import MongoClient

# Connect to MongoDB
client = MongoClient('mongodb+srv://SAPP_SERVER:CCKB_2004@sapp.bba6dy5.mongodb.net/?retryWrites=true&w=majority')

#db = client['company_data']
#collection = db['glassdoor_jobs']
df = pd.read_csv('./glassdoor_jobs.csv')
df.rename(columns={'Unnamed: 0': 'index'}, inplace=True)
df.set_index('index', inplace=True)
df.drop(columns=['Founded', 'Industry','Competitors'], axis=1, inplace=True)
df.head(1)
data = df.to_dict('records')
#db.glassdoor_jobs.insert_many(data)
data

ConfigurationError: The resolution lifetime expired after 21.228 seconds: Server Do53:192.168.2.1@53 answered The DNS operation timed out.; Server Do53:192.168.2.1@53 answered The DNS operation timed out.; Server Do53:192.168.2.1@53 answered The DNS operation timed out.; Server Do53:192.168.2.1@53 answered The DNS operation timed out.; Server Do53:192.168.2.1@53 answered The DNS operation timed out.; Server Do53:192.168.2.1@53 answered The DNS operation timed out.; Server Do53:192.168.2.1@53 answered The DNS operation timed out.

In [57]:
job_title = input("Enter job title keyword: ")
filtered_df = df[df['Job Title'].str.contains(job_title, case=False, na=False)]
filtered_df

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Type of ownership,Sector,Revenue
index,,,,,,,,,,,
0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,Company - Private,Aerospace & Defense,$50 to $100 million (USD)
1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,Other Organization,Health Care,$2 to $5 billion (USD)
2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,Company - Private,Business Services,$100 to $500 million (USD)
3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,Government,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD)
4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,Company - Private,Business Services,Unknown / Non-Applicable
...,...,...,...,...,...,...,...,...,...,...,...
934,Senior Insurance Data Scientist,$107K-$173K (Glassdoor est.),"What We'll Bring:\n\nAt TransUnion, we have a ...",3.9,TransUnion\n3.9,"Chicago, IL","Chicago, IL",5001 to 10000 employees,Company - Public,Finance,$1 to $2 billion (USD)
935,Senior Data Science Systems Engineer,$56K-$99K (Glassdoor est.),"MITRE’s Army Concepts, Platforms and Theater O...",3.2,MITRE\n3.2,"Hampton, VA","Bedford, MA",5001 to 10000 employees,Nonprofit Organization,Government,$1 to $2 billion (USD)
947,Data Science Project Manager,$37K-$100K (Glassdoor est.),"At MassMutual, we are passionate about helping...",3.6,MassMutual\n3.6,"Boston, MA","Springfield, MA",5001 to 10000 employees,Company - Private,Insurance,$10+ billion (USD)
949,"Principal, Data Science - Advanced Analytics",$86K-$137K (Glassdoor est.),IQVIA is the leading human data science compan...,3.6,IQVIA\n3.6,"Plymouth Meeting, PA","Durham, NC",10000+ employees,Company - Public,Biotech & Pharmaceuticals,$2 to $5 billion (USD)
953,Data Science Manager,$95K-$160K (Glassdoor est.),Data Science ManagerResponsibilities:\n\nOvers...,3.2,"Numeric, LLC\n3.2","Allentown, PA","Chadds Ford, PA",1 to 50 employees,Company - Private,Business Services,$5 to $10 million (USD)